// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Fri, 02 Oct 2015 14:49:27 GMT

using System.Reflection;

[assembly: AssemblyVersion("1.3.18902.0")]
[assembly: AssemblyFileVersion("1.3.18902.1449")]
