// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Tue, 23 Jan 2018 17:40:39 GMT

using System.Reflection;

[assembly: AssemblyVersion("3.0.21623.0")]
[assembly: AssemblyFileVersion("3.0.21623.1740")]
