// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// Generated: Wed, 31 May 2017 14:59:13 GMT

using System.Reflection;

[assembly: AssemblyVersion("2.6.20831.0")]
[assembly: AssemblyFileVersion("2.6.20831.1459")]
